maintainer        'Opscode, Inc.'
maintainer_email  'cookbooks@opscode.com'
license           'Apache 2.0'
description       'Installs and configures chef'
version           '0.1'
recipe            'chef::client', 'Sets up a client to talk to a chef-server'
