#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'

include FileUtils

cd('/cdrom/bundle/rubygems-1.3.5') { system 'ruby setup.rb' }
ln_sf '/usr/bin/gem1.8', '/usr/bin/gem'

cp_r  '/cdrom/bundle/rubygems', '/srv'
File.open('/etc/gemrc', 'w') do |io|
  YAML.dump({ :sources => ['file:/srv/rubygems/'] }, io)
end
