#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

system 'gem install chef        --no-rdoc --no-ri'
system 'gem install chef-deploy --no-rdoc --no-ri'

cd '/cdrom/bundle/chef' do
  mkdir_p '/etc/chef'
  mkdir_p '/var/log/chef'

  install 'solo.rb',   '/etc/chef/solo.rb',     :mode => 0644
  install 'crontab',   '/etc/cron.d/chef',      :mode => 0644
  install 'logrotate', '/etc/logrotate.d/chef', :mode => 0644

  touch '/var/log/chef/solo.log'
end
